# Generated by Django 6.0.3 on 2026-04-01 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciselog',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='exerciselog',
            name='session',
        ),
        migrations.RemoveField(
            model_name='setrecord',
            name='exercise_log',
        ),
        migrations.AlterModelOptions(
            name='workoutsession',
            options={'ordering': ['-started_at']},
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='start_time',
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('STRENGTH', 'Fuerza'), ('CARDIO', 'Cardiovascular'), ('FULL_BODY', 'Cuerpo Completo')], default='STRENGTH', max_length=20),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SessionExerciseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('WARMUP', 'Calentamiento'), ('MAIN', 'Principal'), ('COOLDOWN', 'Cardio Final')], default='MAIN', max_length=10)),
                ('entry_type', models.CharField(choices=[('STRENGTH', 'Fuerza'), ('CARDIO', 'Cardio'), ('FULL_BODY', 'Cuerpo Completo')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_entries', to='workouts.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='workouts.workoutsession')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FullBodyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_mode', models.CharField(choices=[('NONE', 'Solo marcar ejercicio'), ('TIME', 'Tiempo total'), ('SETS_REPS', 'Series y repeticiones')], default='NONE', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('sets_done', models.PositiveIntegerField(blank=True, null=True)),
                ('reps_done', models.PositiveIntegerField(blank=True, null=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='full_body_data', to='workouts.sessionexerciseentry')),
            ],
        ),
        migrations.CreateModel(
            name='CardioEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.PositiveIntegerField()),
                ('distance_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distance_unit', models.CharField(choices=[('steps', 'Pasos'), ('km', 'Kilometros')], max_length=10)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cardio_data', to='workouts.sessionexerciseentry')),
            ],
        ),
        migrations.CreateModel(
            name='StrengthSetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField()),
                ('reps_done', models.PositiveIntegerField()),
                ('weight_lifted', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strength_sets', to='workouts.sessionexerciseentry')),
            ],
            options={
                'ordering': ['set_number'],
            },
        ),
        migrations.DeleteModel(
            name='CardioLog',
        ),
        migrations.DeleteModel(
            name='ExerciseLog',
        ),
        migrations.DeleteModel(
            name='SetRecord',
        ),
        migrations.AddConstraint(
            model_name='strengthsetentry',
            constraint=models.UniqueConstraint(fields=('entry', 'set_number'), name='unique_strength_set_per_entry'),
        ),
    ]
